### ISSUE TITLE
URL field for radio stations

### ISSUE THREAD

**Issue by fkuehne** [elthariel/icast#31]
IMO, it would be very useful to have a URL field per station to link to their official website. :)

**Comment by elthariel** [comment]
Hi,

Thank you very much for the suggestion @fkuehne. This is a great idea, which is actually already implemented ;). The link is available through the api and is displayed on the basic frontend whenever it is available. The problem is we don't have an official website url for all the stations. We have the user contributed content feature to help improve this.

By
